services:
  - type: web
    name: nonfraud-ai
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ARKESEL_API_KEY
        sync: false
      - key: ARKESEL_SENDER_ID
        sync: false
